import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Layout/Navbar";
import Footer from "@/components/Layout/Footer";
// import NextTopLoader from "nextjs-toploader";
import { DM_Sans } from "next/font/google";
import { PopupProvider } from "@/components/UI/Popup"; // Import the PopupProvider

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "FLMS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Wrap the entire content with PopupProvider */}
        <PopupProvider>
          {/* <NextTopLoader color="#A77523" /> */}
          <Navbar />
          <div id="page-body">{children}</div>
          <Footer />
        </PopupProvider>
      </body>
    </html>
  );
}