import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Layout/Navbar";
import Footer from "@/components/Layout/Footer";
import { PopupProvider } from "@/components/UI/Popup";
import { FlmsPopupProvider } from "@/components/UI/FLMS.Popup";
import SessionChecker from "@/components/SessionChecker"; // Import the session checker

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "FLMS",
  description: "Generated by create next app",
  icons: {
    icon: "/DBPLogo.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <FlmsPopupProvider>
        <PopupProvider>
          <SessionChecker /> {/* This will run the session check */}
          <Navbar />
          <div id="page-body">{children}</div>
          <Footer />
        </PopupProvider>
        </FlmsPopupProvider>
      </body>
    </html>
  );
}
